# Generated by Django 4.0.3 on 2022-03-02 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homes Page', 'verbose_name_plural': 'Home Pages'},
        ),
    ]
