# Generated by Django 4.0.3 on 2022-03-05 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0011_alter_homepage_content_homepagecarouselbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselbanner',
            name='carousel_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepagecarouselbanner',
            name='carousel_subtitle',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepagecarouselbanner',
            name='carousel_title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
