# Generated by Django 4.0.3 on 2022-03-05 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='FaceBook URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Teitter URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Youtube Channel URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Linkedin URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
