# Generated by Django 4.0.3 on 2022-03-24 12:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, help_text="Don't Change This Field")),
                ('title', models.CharField(choices=[('Main', 'Main')], max_length=100)),
                ('content', wagtail.core.fields.StreamField([('schools', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('admissions', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('home', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('news_And_Events', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('careers', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('alumni', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('about_Us', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('contact_Us', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True)),
                ('logo', models.ForeignKey(help_text='Add You Navigation Logo', null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
